/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import * as THREE from 'three';
import * as SkeletonUtils from 'three/addons/utils/SkeletonUtils.js';

export default function CharacterFloating(props) {
  const group = useRef();
  const { scene, materials } = useGLTF("./models/mascotFromMixamo.glb");
  const copiedCharacter = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const {nodes} = useGraph(copiedCharacter);

  const { animations: floatingAnimation } = useFBX("./animations/TreadingWater.fbx");

  floatingAnimation[0].name = "Floating";
  const { actions } = useAnimations(floatingAnimation, group)

  useFrame((state) => {
    const target = new THREE.Vector3(state.mouse.x, state.mouse.y, 1);
    

    group.current.traverse((object) => {
      if (object.name === "mixamorigHead") {
        object.lookAt(target);
      }
    });
  });

  useEffect(() => {
    actions["Floating"].reset().play();
  }, [])



  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group 
          name="Armature" 
          rotation={[0, 0, 0]} 
          scale={0.7}
        >
          <skinnedMesh
            name="CharacterRetopo"
            geometry={nodes.CharacterRetopo.geometry}
            skeleton={nodes.CharacterRetopo.skeleton}
            material={materials["Material.004"]}          
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/mascotFromMixamo.glb");

